language: r
cache: packages

branches:
  except:
    - gh-pages

script:
  - Rscript -e "install.packages('devtools')"  
  - Rscript -e "devtools::install_github('emitanaka/xaringan');devtools::install_github('emitanaka/icon');devtools::install_github('emitanaka/anicon')"

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: pages
  local_dir: /
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master